AWSTemplateFormatVersion: '2010-09-09'
Description: >
  otlp2parquet - OpenTelemetry logs to Parquet on S3 (One-Click Deployment)

  Deploys otlp2parquet Lambda function using pre-built container image.
  No local tools required - just click "Create Stack"!

# Metadata for better CloudFormation console experience
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Storage Configuration"
        Parameters:
          - BucketName
      - Label:
          default: "Lambda Configuration"
        Parameters:
          - LogRetentionDays
          - ContainerImage
    ParameterLabels:
      BucketName:
        default: "S3 Bucket Name (must be globally unique)"
      LogRetentionDays:
        default: "CloudWatch Log Retention (Days)"
      ContainerImage:
        default: "Lambda Container Image URI"

# Parameters
Parameters:
  BucketName:
    Type: String
    Description: >
      S3 bucket name for storing Parquet files (must be globally unique).
      Leave empty to auto-generate a name.
    Default: ""
    AllowedPattern: ^$|^[a-z0-9][a-z0-9-]*[a-z0-9]$
    ConstraintDescription: Must be empty or lowercase alphanumeric with hyphens

  LogRetentionDays:
    Type: Number
    Description: Number of days to retain Lambda logs in CloudWatch
    Default: 7
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]

  ContainerImage:
    Type: String
    Description: Lambda container image URI from ECR Public or GitHub Container Registry
    Default: public.ecr.aws/otlp2parquet/otlp2parquet:latest
    # NOTE: This image must be published first. For now, users should build and push their own.
    # See Dockerfile.lambda for build instructions.

Conditions:
  CreateBucket: !Equals [!Ref BucketName, ""]
  UseProvidedBucket: !Not [!Equals [!Ref BucketName, ""]]

Resources:
  # S3 bucket for Parquet files
  AutoGeneratedBucket:
    Type: AWS::S3::Bucket
    Condition: CreateBucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: INTELLIGENT_TIERING
      Tags:
        - Key: Application
          Value: otlp2parquet
        - Key: ManagedBy
          Value: CloudFormation

  ProvidedBucket:
    Type: AWS::S3::Bucket
    Condition: UseProvidedBucket
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: INTELLIGENT_TIERING
      Tags:
        - Key: Application
          Value: otlp2parquet
        - Key: ManagedBy
          Value: CloudFormation

  # IAM role for Lambda execution
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3WriteAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !If
                    - CreateBucket
                    - !GetAtt AutoGeneratedBucket.Arn
                    - !Sub 'arn:aws:s3:::${BucketName}'
                  - !If
                    - CreateBucket
                    - !Sub '${AutoGeneratedBucket.Arn}/*'
                    - !Sub 'arn:aws:s3:::${BucketName}/*'

  # CloudWatch Logs group
  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/otlp2parquet
      RetentionInDays: !Ref LogRetentionDays

  # Lambda function using container image
  OtlpToParquetFunction:
    Type: AWS::Lambda::Function
    DependsOn: FunctionLogGroup
    Properties:
      FunctionName: otlp2parquet
      PackageType: Image
      Code:
        ImageUri: !Ref ContainerImage
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - arm64  # Graviton2 for 20% cost savings
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          RUST_LOG: info
          STORAGE_BACKEND: s3
          S3_BUCKET: !If
            - CreateBucket
            - !Ref AutoGeneratedBucket
            - !Ref BucketName
          S3_REGION: !Ref AWS::Region
      LoggingConfig:
        LogFormat: JSON
        ApplicationLogLevel: INFO
        SystemLogLevel: INFO

  # Function URL for public HTTP access
  FunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt OtlpToParquetFunction.Arn
      AuthType: NONE  # Public access - change to AWS_IAM for authentication
      Cors:
        AllowOrigins:
          - "*"
        AllowMethods:
          - POST
        AllowHeaders:
          - content-type
          - x-amz-date
          - authorization
        MaxAge: 300

  # Permission for Function URL invocation
  FunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref OtlpToParquetFunction
      FunctionUrlAuthType: NONE
      Action: lambda:InvokeFunctionUrl
      Principal: "*"

Outputs:
  FunctionUrl:
    Description: "🎯 OTLP HTTP Endpoint - Send your logs here!"
    Value: !GetAtt FunctionUrl.FunctionUrl
    Export:
      Name: !Sub '${AWS::StackName}-FunctionUrl'

  BucketName:
    Description: "📦 S3 Bucket Name - Where your Parquet files are stored"
    Value: !If
      - CreateBucket
      - !Ref AutoGeneratedBucket
      - !Ref BucketName
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  FunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt OtlpToParquetFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionArn'

  ConsoleUrl:
    Description: "📊 AWS Lambda Console - View your function"
    Value: !Sub 'https://console.aws.amazon.com/lambda/home?region=${AWS::Region}#/functions/${OtlpToParquetFunction}'

  S3ConsoleUrl:
    Description: "📂 S3 Console - Browse your Parquet files"
    Value: !If
      - CreateBucket
      - !Sub 'https://s3.console.aws.amazon.com/s3/buckets/${AutoGeneratedBucket}?region=${AWS::Region}'
      - !Sub 'https://s3.console.aws.amazon.com/s3/buckets/${BucketName}?region=${AWS::Region}'

  TestCommand:
    Description: "🧪 Test your deployment"
    Value: !Sub |
      curl -X POST ${FunctionUrl.FunctionUrl}v1/logs \
        -H "Content-Type: application/x-protobuf" \
        --data-binary @test-payload.pb

  NextSteps:
    Description: "📖 What to do next"
    Value: |
      1. Copy the Function URL from outputs above
      2. Configure your OpenTelemetry SDK: OTEL_EXPORTER_OTLP_ENDPOINT=<Function URL>
      3. Send test logs using the Test Command
      4. View Parquet files in S3 Console (link above)
      5. Query with DuckDB: read_parquet('s3://your-bucket/logs/**/*.parquet')
