// quill-proto - OpenTelemetry Protocol Definitions
//
// This crate contains the generated protobuf code for OTLP.
// The code is generated at build time from the OpenTelemetry proto files.

// Include generated protobuf code
// This will be generated by build.rs once we add the proto files
pub mod opentelemetry {
    pub mod proto {
        pub mod collector {
            pub mod logs {
                pub mod v1 {
                    // TODO: Include generated code once proto files are added
                    // include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.collector.logs.v1.rs"));
                }
            }
        }
        pub mod logs {
            pub mod v1 {
                // TODO: Include generated code
                // include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.logs.v1.rs"));
            }
        }
        pub mod common {
            pub mod v1 {
                // TODO: Include generated code
                // include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.common.v1.rs"));
            }
        }
        pub mod resource {
            pub mod v1 {
                // TODO: Include generated code
                // include!(concat!(env!("OUT_DIR"), "/opentelemetry.proto.resource.v1.rs"));
            }
        }
    }
}
