AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  otlp2parquet - OpenTelemetry logs to Parquet on S3

  Deploys a Lambda function with Function URL for OTLP HTTP ingestion.
  Uses ARM64 (Graviton2) for better price/performance.

# Parameters for easy customization
Parameters:
  BucketName:
    Type: String
    Description: S3 bucket name for Parquet files (will be created)
    Default: otlp-logs
    AllowedPattern: ^[a-z0-9][a-z0-9-]*[a-z0-9]$
    ConstraintDescription: Must be a valid S3 bucket name (lowercase, hyphens only)

  LogRetentionDays:
    Type: Number
    Description: CloudWatch Logs retention in days
    Default: 7
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: provided.al2023  # Custom runtime for Rust
    Architectures:
      - arm64  # Graviton2 - 20% cheaper and faster for Rust
    Environment:
      Variables:
        RUST_LOG: info
        # WARNING: Batching on Lambda can cause data loss!
        # Lambda invocations are stateless - unflushed batches are lost when invocation ends.
        # Only enable if you have high-volume sustained traffic (200K rows, 128MB, or 10s threshold).
        OTLP2PARQUET_BATCHING_ENABLED: "false"

Resources:
  # Lambda function
  OtlpToParquetFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: otlp2parquet
        CargoPackage: otlp2parquet-lambda
    Properties:
      CodeUri: ../..  # Points to workspace root for cargo build
      Handler: bootstrap  # Required for custom runtime
      Description: Ingests OTLP logs and writes Parquet to S3
      Environment:
        Variables:
          OTLP2PARQUET_S3_BUCKET: !Ref LogsBucket
          OTLP2PARQUET_S3_REGION: !Ref AWS::Region
          # NOTE: For local testing with sam local invoke:
          # Edit .aws-sam/build/template.yaml to add OTLP2PARQUET_S3_ENDPOINT, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
          # See docs/get-started/deployment/aws-lambda.md for details
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref LogsBucket
      # HTTP API events for local testing with SAM
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
            PayloadFormatVersion: "2.0"
      # Function URL for HTTP access (no auth - configure as needed)
      FunctionUrlConfig:
        AuthType: NONE  # Change to AWS_IAM for authenticated access
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - POST
          AllowHeaders:
            - content-type
          MaxAge: 300
      LoggingConfig:
        LogFormat: JSON
        ApplicationLogLevel: INFO
        SystemLogLevel: INFO
        LogGroup: !Ref FunctionLogGroup

  # CloudWatch Logs
  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${OtlpToParquetFunction}
      RetentionInDays: !Ref LogRetentionDays

  # S3 bucket for Parquet files
  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          # Optional: Transition to cheaper storage classes
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: INTELLIGENT_TIERING
      Tags:
        - Key: Application
          Value: otlp2parquet
        - Key: ManagedBy
          Value: SAM

Outputs:
  FunctionUrl:
    Description: OTLP HTTP endpoint URL
    Value: !GetAtt OtlpToParquetFunctionUrl.FunctionUrl
    Export:
      Name: !Sub ${AWS::StackName}-FunctionUrl

  FunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt OtlpToParquetFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-FunctionArn

  BucketName:
    Description: S3 bucket for Parquet files
    Value: !Ref LogsBucket
    Export:
      Name: !Sub ${AWS::StackName}-BucketName

  BucketArn:
    Description: S3 bucket ARN
    Value: !GetAtt LogsBucket.Arn
    Export:
      Name: !Sub ${AWS::StackName}-BucketArn

  # Example curl command
  TestCommand:
    Description: Test the endpoint with curl
    Value: !Sub |
      curl -X POST ${OtlpToParquetFunctionUrl.FunctionUrl}v1/logs \
        -H "Content-Type: application/x-protobuf" \
        --data-binary @test-payload.pb
