AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  otlp2parquet - OpenTelemetry logs to Parquet on S3

  Deploys a Lambda function with Function URL for OTLP HTTP ingestion.
  Uses ARM64 (Graviton2) for better price/performance.

# Parameters for easy customization
Parameters:
  CatalogMode:
    Type: String
    Description: Catalog mode - 'iceberg' for S3 Tables catalog, 'none' for plain Parquet files
    Default: iceberg
    AllowedValues:
      - iceberg
      - none

  BucketName:
    Type: String
    Description: S3 bucket name for Parquet files (will be created)
    Default: otlp-logs
    AllowedPattern: ^[a-z0-9][a-z0-9-]*[a-z0-9]$
    ConstraintDescription: Must be a valid S3 bucket name (lowercase, hyphens only)

  LogRetentionDays:
    Type: Number
    Description: CloudWatch Logs retention in days
    Default: 7
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]

Conditions:
  UseIcebergCatalog: !Equals [!Ref CatalogMode, iceberg]
  UsePlainParquet: !Equals [!Ref CatalogMode, none]

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: provided.al2023  # Custom runtime for Rust
    Architectures:
      - arm64  # Graviton2 - 20% cheaper and faster for Rust
    Environment:
      Variables:
        RUST_LOG: info

Resources:
  # Lambda function
  OtlpToParquetFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        CargoPackage: otlp2parquet-lambda
    Properties:
      CodeUri: .  # Points to lambda crate directory
      Handler: bootstrap  # Required for custom runtime
      Description: Ingests OTLP logs and writes Parquet to S3
      Environment:
        Variables:
          OTLP2PARQUET_CATALOG_MODE: !Ref CatalogMode
          OTLP2PARQUET_STORAGE_S3_BUCKET: !If [UsePlainParquet, !Ref DataBucket, !Ref AWS::NoValue]
          OTLP2PARQUET_STORAGE_S3_REGION: !If [UsePlainParquet, !Ref AWS::Region, !Ref AWS::NoValue]
          OTLP2PARQUET_ICEBERG_BUCKET_ARN: !If [UseIcebergCatalog, !GetAtt S3TablesBucket.Arn, !Ref AWS::NoValue]
          OTLP2PARQUET_ICEBERG_NAMESPACE: otlp
          # NOTE: For local testing with sam local invoke:
          # Edit .aws-sam/build/template.yaml to add OTLP2PARQUET_STORAGE_S3_ENDPOINT, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
          # See docs/guides/lambda-local-development.md for details
      Policies:
        - !If
          - UsePlainParquet
          - S3CrudPolicy:
              BucketName: !Ref DataBucket
          - !Ref AWS::NoValue
        - !If
          - UseIcebergCatalog
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3tables:GetTable
                  - s3tables:GetTableMetadataLocation
                  - s3tables:CreateTable
                  - s3tables:UpdateTableMetadataLocation
                  - s3tables:GetNamespace
                  - s3tables:CreateNamespace
                  - s3tables:PutTableData
                  - s3tables:GetTableData
                Resource:
                  - !Sub '${S3TablesBucket.Arn}/*'
                  - !GetAtt S3TablesBucket.Arn
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub '${S3TablesBucket.Arn}/*'
                  - !GetAtt S3TablesBucket.Arn
          - !Ref AWS::NoValue
      # HTTP API events for local testing with SAM
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
            PayloadFormatVersion: "2.0"
      # Function URL for HTTP access with IAM authentication
      # Clients must sign requests with AWS SigV4 using valid AWS credentials
      # See "Authentication Examples" section in Outputs for usage
      FunctionUrlConfig:
        AuthType: AWS_IAM  # Requires AWS SigV4 signed requests
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - POST
          AllowHeaders:
            - content-type
            - authorization
            - x-amz-date
            - x-amz-security-token
          MaxAge: 300
      LoggingConfig:
        LogFormat: JSON
        ApplicationLogLevel: INFO
        SystemLogLevel: INFO
        LogGroup: !Ref FunctionLogGroup

  # CloudWatch Logs
  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${OtlpToParquetFunction}
      RetentionInDays: !Ref LogRetentionDays

  # S3 bucket for plain Parquet mode
  DataBucket:
    Type: AWS::S3::Bucket
    Condition: UsePlainParquet
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldData
            Status: Enabled
            ExpirationInDays: 90

  # S3 Tables bucket for Iceberg mode
  S3TablesBucket:
    Type: AWS::S3Tables::TableBucket
    Condition: UseIcebergCatalog
    Properties:
      TableBucketName: !Ref BucketName

Outputs:
  FunctionUrl:
    Description: OTLP HTTP endpoint URL
    Value: !GetAtt OtlpToParquetFunctionUrl.FunctionUrl
    Export:
      Name: !Sub ${AWS::StackName}-FunctionUrl

  FunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt OtlpToParquetFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-FunctionArn

  CatalogMode:
    Description: Catalog mode (iceberg or none)
    Value: !Ref CatalogMode

  DataLocation:
    Description: Data storage location
    Value: !If
      - UsePlainParquet
      - !Sub 's3://${DataBucket}'
      - !GetAtt S3TablesBucket.Arn

  S3TablesBucketArn:
    Condition: UseIcebergCatalog
    Description: S3 Tables bucket ARN (Iceberg catalog)
    Value: !GetAtt S3TablesBucket.Arn

  PlainParquetBucket:
    Condition: UsePlainParquet
    Description: S3 bucket name for plain Parquet files
    Value: !Ref DataBucket

  ExampleDuckDBQuery:
    Condition: UsePlainParquet
    Description: Example DuckDB query for plain Parquet mode
    Value: !Sub |
      -- Query logs from S3
      SELECT * FROM read_parquet('s3://${DataBucket}/logs/**/*.parquet') LIMIT 10;
