AWSTemplateFormatVersion: '2010-09-09'
Description: 'otlp2parquet Lambda with S3 Tables (Apache Iceberg)'

Parameters:
  LambdaCodeBucket:
    Type: String
    Description: S3 bucket containing the Lambda deployment package

  LambdaCodeKey:
    Type: String
    Description: S3 key for the Lambda zip file
    Default: lambda/otlp2parquet-lambda.zip

  LambdaArchitecture:
    Type: String
    Description: Lambda architecture (arm64 recommended for better price/performance)
    Default: arm64
    AllowedValues:
      - arm64
      - x86_64

Resources:
  # S3 Bucket - Stores Parquet data files for Iceberg tables
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'otlp2parquet-data-${AWS::StackName}-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Lambda execution role with Glue and S3 permissions
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        # Basic execution role for CloudWatch Logs
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3DataAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # S3 object permissions for Parquet files in data bucket
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt DataBucket.Arn
                  - !Sub '${DataBucket.Arn}/*'
        - PolicyName: GlueAndLakeFormationAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetTable
                  - glue:CreateTable
                  - glue:UpdateTable
                  - lakeformation:GetDataAccess
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub 'arn:aws:s3:::${DataBucket}/*'

  # CloudWatch log group with 7-day retention for cost optimization
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-ingest'
      RetentionInDays: 7

  # Lambda function running otlp2parquet Rust binary
  OtlpIngestFunction:
    Type: AWS::Lambda::Function
    DependsOn: LambdaLogGroup
    Properties:
      FunctionName: !Sub '${AWS::StackName}-ingest'
      Runtime: provided.al2023
      Handler: bootstrap
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - !Ref LambdaArchitecture
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          # Storage configuration
          OTLP2PARQUET_STORAGE_BACKEND: 's3'
          OTLP2PARQUET_S3_BUCKET: !Ref DataBucket
          OTLP2PARQUET_S3_REGION: !Ref AWS::Region

          # Iceberg via AWS Glue Data Catalog
          OTLP2PARQUET_ICEBERG_ENABLED: 'true'
          OTLP2PARQUET_ICEBERG_REST_URI: !Sub 'https://glue.${AWS::Region}.amazonaws.com/iceberg'
          OTLP2PARQUET_ICEBERG_WAREHOUSE: !Ref AWS::AccountId
          OTLP2PARQUET_ICEBERG_NAMESPACE: 'otel'
          OTLP2PARQUET_ICEBERG_DATA_LOCATION: !Sub 's3://${DataBucket}'

          # Logging
          RUST_LOG: 'info'

Outputs:
  LambdaFunctionArn:
    Description: Lambda function ARN (use for testing with aws lambda invoke)
    Value: !GetAtt OtlpIngestFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaArn'

  LambdaFunctionName:
    Description: Lambda function name
    Value: !Ref OtlpIngestFunction
    Export:
      Name: !Sub '${AWS::StackName}-LambdaName'

  LambdaRoleArn:
    Description: Lambda execution role ARN (for Lake Formation permissions)
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaRoleArn'

  DataBucketName:
    Description: S3 bucket storing Parquet data files (Iceberg table data)
    Value: !Ref DataBucket
    Export:
      Name: !Sub '${AWS::StackName}-DataBucket'

  GlueCatalogId:
    Description: AWS Glue catalog ID (account ID) for Iceberg tables
    Value: !Ref AWS::AccountId
    Export:
      Name: !Sub '${AWS::StackName}-GlueCatalogId'

  GlueDatabase:
    Description: Glue database name for Iceberg tables
    Value: 'otel'
    Export:
      Name: !Sub '${AWS::StackName}-GlueDatabase'

  IcebergRestEndpoint:
    Description: AWS Glue Iceberg REST catalog endpoint
    Value: !Sub 'https://glue.${AWS::Region}.amazonaws.com/iceberg'
    Export:
      Name: !Sub '${AWS::StackName}-IcebergEndpoint'

  Region:
    Description: AWS Region where resources are deployed
    Value: !Ref AWS::Region
    Export:
      Name: !Sub '${AWS::StackName}-Region'
