AWSTemplateFormatVersion: '2010-09-09'
Description: 'otlp2parquet Lambda with S3 Tables (Apache Iceberg)'

Parameters:
  LambdaCodeBucket:
    Type: String
    Description: S3 bucket containing the Lambda deployment package

  LambdaCodeKey:
    Type: String
    Description: S3 key for the Lambda zip file
    Default: lambda/otlp2parquet-lambda.zip

  LambdaArchitecture:
    Type: String
    Description: Lambda architecture (arm64 recommended for better price/performance)
    Default: arm64
    AllowedValues:
      - arm64
      - x86_64

  S3TablesBucketName:
    Type: String
    Description: Name for the S3 Tables bucket (must be globally unique)
    Default: ''

Resources:
  # S3 Tables Bucket - Managed Iceberg tables with built-in catalog
  S3TablesBucket:
    Type: AWS::S3Tables::TableBucket
    Properties:
      TableBucketName: !If
        - HasCustomBucketName
        - !Ref S3TablesBucketName
        - !Sub 'otlp2parquet-${AWS::StackName}-${AWS::AccountId}'

  # S3 Tables Namespace - Logical grouping for Iceberg tables
  S3TablesNamespace:
    Type: AWS::S3Tables::TableBucketNamespace
    Properties:
      TableBucketARN: !GetAtt S3TablesBucket.Arn
      Namespace: 'otel'

  # Lambda execution role with S3 Tables permissions
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        # Basic execution role for CloudWatch Logs
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3TablesAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # S3 Tables permissions for Iceberg operations
              - Effect: Allow
                Action:
                  - s3tables:GetTable
                  - s3tables:GetTableMetadataLocation
                  - s3tables:CreateTable
                  - s3tables:UpdateTableMetadataLocation
                  - s3tables:GetNamespace
                  - s3tables:CreateNamespace
                Resource:
                  - !GetAtt S3TablesBucket.Arn
                  - !Sub '${S3TablesBucket.Arn}/*'
              # S3 object permissions for Parquet data files
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt S3TablesBucket.Arn
                  - !Sub '${S3TablesBucket.Arn}/*'

  # CloudWatch log group with 7-day retention for cost optimization
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-ingest'
      RetentionInDays: 7

  # Lambda function running otlp2parquet Rust binary
  OtlpIngestFunction:
    Type: AWS::Lambda::Function
    DependsOn: LambdaLogGroup
    Properties:
      FunctionName: !Sub '${AWS::StackName}-ingest'
      Runtime: provided.al2023
      Handler: bootstrap
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - !Ref LambdaArchitecture
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          # Storage configuration
          OTLP2PARQUET_STORAGE_BACKEND: 's3'
          OTLP2PARQUET_S3_REGION: !Ref AWS::Region

          # S3 Tables Iceberg integration
          OTLP2PARQUET_ICEBERG_BUCKET_ARN: !GetAtt S3TablesBucket.Arn

          # Logging
          RUST_LOG: 'debug'

Conditions:
  HasCustomBucketName: !Not [!Equals [!Ref S3TablesBucketName, '']]

Outputs:
  LambdaFunctionArn:
    Description: Lambda function ARN (use for testing with aws lambda invoke)
    Value: !GetAtt OtlpIngestFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaArn'

  LambdaFunctionName:
    Description: Lambda function name
    Value: !Ref OtlpIngestFunction
    Export:
      Name: !Sub '${AWS::StackName}-LambdaName'

  LambdaRoleArn:
    Description: Lambda execution role ARN
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaRoleArn'

  S3TablesBucketArn:
    Description: S3 Tables bucket ARN
    Value: !GetAtt S3TablesBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TableBucketArn'

  S3TablesBucketName:
    Description: S3 Tables bucket name
    Value: !Ref S3TablesBucket
    Export:
      Name: !Sub '${AWS::StackName}-TableBucketName'

  S3TablesNamespace:
    Description: S3 Tables namespace for Iceberg tables
    Value: !Ref S3TablesNamespace
    Export:
      Name: !Sub '${AWS::StackName}-Namespace'

  Region:
    Description: AWS Region where resources are deployed
    Value: !Ref AWS::Region
    Export:
      Name: !Sub '${AWS::StackName}-Region'
