AWSTemplateFormatVersion: '2010-09-09'
Description: 'otlp2parquet Lambda with S3 Tables (Apache Iceberg)'

Parameters:
  LambdaCodeBucket:
    Type: String
    Description: S3 bucket containing the Lambda deployment package

  LambdaCodeKey:
    Type: String
    Description: S3 key for the Lambda zip file
    Default: lambda/otlp2parquet-lambda.zip

  LambdaArchitecture:
    Type: String
    Description: Lambda architecture (arm64 recommended for better price/performance)
    Default: arm64
    AllowedValues:
      - arm64
      - x86_64

  S3TablesBucketName:
    Type: String
    Description: Name for the S3 Tables bucket (must be globally unique)
    Default: ''

  ExistingS3TablesBucketArn:
    Type: String
    Description: Optional - Use an existing S3 Tables bucket ARN instead of creating a new one (format arn:aws:s3tables:region:account:bucket/name)
    Default: ''

Resources:
  # S3 Tables Bucket - Managed Iceberg tables with built-in catalog (only created if not using existing)
  S3TablesBucket:
    Type: AWS::S3Tables::TableBucket
    Condition: CreateNewBucket
    Properties:
      TableBucketName: !If
        - HasCustomBucketName
        - !Ref S3TablesBucketName
        - !Sub 'otlp2parquet-${AWS::StackName}-${AWS::AccountId}'

  # S3 Tables Namespace - Logical grouping for Iceberg tables (only created if not using existing)
  S3TablesNamespace:
    Type: AWS::S3Tables::Namespace
    Condition: CreateNewBucket
    Properties:
      TableBucketARN: !GetAtt S3TablesBucket.TableBucketARN
      Namespace: 'otlp'

  # Lambda execution role with S3 Tables permissions
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        # Basic execution role for CloudWatch Logs
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3TablesAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # S3 Tables permissions - S3 Tables manages underlying S3 storage
              # Use wildcard for table/namespace resources since ARN format is:
              # arn:aws:s3tables:region:account:bucket/name/namespace/ns/table/tbl
              - Effect: Allow
                Action:
                  - s3tables:*
                Resource:
                  - !If [CreateNewBucket, !GetAtt S3TablesBucket.TableBucketARN, !Ref ExistingS3TablesBucketArn]
                  - !If [CreateNewBucket, !Sub '${S3TablesBucket.TableBucketARN}/*', !Sub '${ExistingS3TablesBucketArn}/*']

  # CloudWatch log group with 7-day retention for cost optimization
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-ingest'
      RetentionInDays: 7

  # Lambda function running otlp2parquet Rust binary
  OtlpIngestFunction:
    Type: AWS::Lambda::Function
    DependsOn: LambdaLogGroup
    Properties:
      FunctionName: !Sub '${AWS::StackName}-ingest'
      Runtime: provided.al2023
      Handler: bootstrap
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - !Ref LambdaArchitecture
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          # S3 Tables Iceberg integration (ARN contains all needed config: region, bucket, etc.)
          OTLP2PARQUET_ICEBERG_BUCKET_ARN: !If [CreateNewBucket, !GetAtt S3TablesBucket.TableBucketARN, !Ref ExistingS3TablesBucketArn]

          # Logging
          RUST_LOG: 'debug'

  # Lambda Function URL for HTTP ingestion
  OtlpFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: AWS_IAM  # Requires AWS SigV4 signed requests
      TargetFunctionArn: !GetAtt OtlpIngestFunction.Arn

  # Lambda permission for Function URL invocations
  OtlpFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref OtlpIngestFunction
      Action: lambda:InvokeFunctionUrl
      Principal: '*'
      FunctionUrlAuthType: NONE

Conditions:
  HasCustomBucketName: !Not [!Equals [!Ref S3TablesBucketName, '']]
  CreateNewBucket: !Equals [!Ref ExistingS3TablesBucketArn, '']

Outputs:
  LambdaFunctionArn:
    Description: Lambda function ARN (use for testing with aws lambda invoke)
    Value: !GetAtt OtlpIngestFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaArn'

  LambdaFunctionName:
    Description: Lambda function name
    Value: !Ref OtlpIngestFunction
    Export:
      Name: !Sub '${AWS::StackName}-LambdaName'

  FunctionUrl:
    Description: Lambda Function URL for OTLP ingestion
    Value: !GetAtt OtlpFunctionUrl.FunctionUrl
    Export:
      Name: !Sub '${AWS::StackName}-FunctionUrl'

  LambdaRoleArn:
    Description: Lambda execution role ARN
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaRoleArn'

  S3TablesBucketArn:
    Description: S3 Tables bucket ARN
    Value: !If [CreateNewBucket, !GetAtt S3TablesBucket.TableBucketARN, !Ref ExistingS3TablesBucketArn]
    Export:
      Name: !Sub '${AWS::StackName}-TableBucketArn'

  S3TablesBucketName:
    Description: S3 Tables bucket name
    Value: !If [CreateNewBucket, !Ref S3TablesBucket, 'Using existing bucket']
    Export:
      Name: !Sub '${AWS::StackName}-TableBucketName'

  S3TablesNamespace:
    Description: S3 Tables namespace for Iceberg tables
    Value: !If [CreateNewBucket, !Ref S3TablesNamespace, 'Using existing namespace']
    Export:
      Name: !Sub '${AWS::StackName}-Namespace'

  Region:
    Description: AWS Region where resources are deployed
    Value: !Ref AWS::Region
    Export:
      Name: !Sub '${AWS::StackName}-Region'

  # Authentication Example
  TestCommand:
    Description: Test the endpoint with curl (requires curl 7.75+ for --aws-sigv4)
    Value: !Sub |
      curl -X POST ${OtlpFunctionUrl.FunctionUrl}v1/logs \
        -H "Content-Type: application/x-protobuf" \
        --data-binary @testdata/logs.pb \
        --aws-sigv4 "aws:amz:${AWS::Region}:lambda" \
        --user "$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY"

      Note: Requires AWS credentials with lambda:InvokeFunctionUrl permission
